=== arup-group/osmox/src/osmox/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "OSMOX config schema",
    "description": "Schema for the OSMOX config JSON file",
    "type": "object",
    "additionalProperties": false,
    "$defs": {
        "stringList": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^(\\*|\\w+)$"
            }
        }
    },
    "required": ["filter", "activity_mapping", "object_features"],
    "properties": {
        "filter": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": { "^(\\*|\\w+)$": { "$ref": "#/$defs/stringList" } }
        },
        "object_features": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["area", "levels", "floor_area", "units", "transit_distance"]
            }
        },
        "distance_to_nearest": { "$ref": "#/$defs/stringList" },
        "default_tags": { "type": "array", "items": { "$ref": "#/$defs/stringList" } },
        "activity_mapping": {
            "type": "object",
            "require": [],
            "additionalProperties": false,
            "patternProperties": {
                "^(\\*|\\w+)$": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^(\\*|\\w+)$": { "$ref": "#/$defs/stringList" } }
                }
            }
        },
        "fill_missing_activities": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["area_tags", "required_acts", "new_tags"],
                "allOf": [
                    {
                        "if": { "properties": {"fill_method": { "const": "spacing" } } },
                        "then": { "required": ["spacing"]  }
                    },
                    {
                        "if": { "properties": {"fill_method": { "const": "point_source" } }, "required": ["fill_method"] },
                        "then": { "required": ["point_source"] },
                        "else": { "required": ["spacing"] }
                    }
                ],
                "properties": {
                    "area_tags": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/stringList"
                        }
                    },
                    "required_acts": {
                        "oneOf": [
                            {"type": "string", "pattern": "^(\\*|\\w+)$"},
                            {"$ref": "#/$defs/stringList"}
                        ]
                    },
                    "new_tags": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/stringList"
                        }
                    },
                    "size": {
                        "type": "array",
                        "minItems": 2,
                        "maxItems": 2,
                        "items": {
                            "type": "number",
                            "exclusiveMinimum": 0
                        }
                    },
                    "spacing": {
                        "type": "array",
                        "minItems": 2,
                        "maxItems": 2,
                        "items": {
                            "type": "number",
                            "exclusiveMinimum": 0
                        }
                    },
                    "fill_method": {
                        "type": "string",
                        "enum": ["spacing", "point_source"]
                    },
                    "point_source": {
                        "type": "string"
                    },
                    "max_existing_acts_fraction": {
                        "type": "number",
                        "minimum": 0
                    }
                }
            }
        }
    }
}

=== arup-group/osmox/tests/fixtures/test_config_infill.json
{
    "filter": {
        "building": [
            "apartments",
            "bungalow",
            "detached",
            "dormitory",
            "hotel",
            "residential",
            "semidetached_house",
            "terrace",
            "commercial",
            "retail",
            "supermarket",
            "industrial",
            "office",
            "warehouse",
            "bakehouse",
            "firestation",
            "government",
            "cathedral",
            "chapel",
            "church",
            "mosque",
            "religous",
            "shrine",
            "synagogue",
            "temple",
            "hospital",
            "kindergarden",
            "school",
            "university",
            "college",
            "sports_hall",
            "stadium",
            "yes"
        ]
    },

    "object_features": ["units", "levels", "area", "floor_area"],

    "distance_to_nearest": ["transit"],

    "default_tags": [["building", "residential"]],

    "activity_mapping": {
        "building": {
            "apartments": ["home"],
            "bungalow": ["home"],
            "detached": ["home"],
            "dormitory": ["home"],
            "hotel": ["home"],
            "residential": ["home"],
            "semidetached_house": ["home"],
            "terrace": ["home"],
            "commercial": ["shop", "work", "delivery"],
            "retail": ["shop", "work", "delivery"],
            "supermarket": ["shop_food", "work", "delivery"],
            "industrial": ["work", "delivery"],
            "office": ["work", "delivery"],
            "warehouse": ["work", "depot", "delivery"],
            "bakehouse": ["work", "depot", "delivery"],
            "firestation": ["work"],
            "government": ["work"],
            "cathedral": ["religous"],
            "chapel": ["religous"],
            "church": ["religous"],
            "mosque": ["religous"],
            "religous": ["religous"],
            "shrine": ["religous"],
            "synagogue": ["religous"],
            "temple": ["religous"],
            "hospital": ["health", "work"],
            "kindergarden": ["education", "work"],
            "school": ["education", "work"],
            "university": ["education", "work"],
            "college": ["education", "work"],
            "sports_hall": ["leisure", "work"],
            "stadium": ["leisure", "work"]
        },
        "amenity": {
            "bar": ["social", "work", "delivery"],
            "pub": ["social", "work", "delivery"],
            "cafe": ["social", "work", "delivery", "food_shop"],
            "fast_food": ["work", "delivery", "food_shop"],
            "food_court": ["work", "delivery", "food_shop"],
            "ice_cream": ["work", "delivery", "food_shop"],
            "restaurant": ["work", "delivery", "food_shop"],
            "college": ["education", "work"],
            "kindergarten": ["education", "work"],
            "language_school": ["education", "work"],
            "library": ["leisure", "work"],
            "music_school": ["leisure", "work"],
            "school": ["leisure", "work"],
            "university": ["leisure", "work"],
            "bank": ["personal_business", "work"],
            "clinic": ["health", "work"],
            "dentist": ["health", "work"],
            "doctors": ["health", "work"],
            "hospital": ["health", "work"],
            "pharmacy": ["shop", "work"],
            "social_facility": ["health", "work"],
            "vetinary": ["personal_business", "work"],
            "arts_centre": ["leisure", "work"],
            "casino": ["leisure", "work"],
            "cinema": ["leisure", "work"],
            "community_centre": ["leisure"],
            "gambling": ["leisure", "work"],
            "studio": ["leisure", "work"],
            "theatre": ["leisure", "work"],
            "courthouse": ["personal_business", "work"],
            "crematorium": ["personal_business", "work"],
            "embassy": ["personal_business", "work"],
            "fire_station": ["work"],
            "funeral_hall": ["personal_business", "work"],
            "internet_cafe": ["leisure", "work"],
            "marketplace": ["shop_food", "work", "delivery"],
            "place_of_worship": ["religous"],
            "police": ["personal_business", "work"],
            "post_box": ["personal_business", "work"],
            "post_depot": ["personal_business", "work"],
            "post_office": ["personal_business", "work"],
            "prison": ["personal_business", "work"],
            "townhall": ["personal_business", "work"]
        },
        "landuse": {
            "commercial": ["shop", "work", "delivery"],
            "industrial": ["shop", "work", "delivery", "depot"],
            "residential": ["home"],
            "retail": ["shop", "work", "delivery"],
            "depot": ["depot"],
            "port": ["depot"],
            "quary": ["depot"],
            "religous": ["religous"]
        },
        "leisure": {
            "adult_gaming_centre": ["leisure", "work"],
            "amusement_arcade": ["leisure", "work"],
            "beach_resort": ["leisure"],
            "dance": ["leisure", "work"],
            "escape_game": ["leisure", "work"],
            "fishing": ["leisure"],
            "fitness_centre": ["leisure", "work"],
            "fitness_station": ["leisure"],
            "garden": ["leisure"],
            "horse_riding": ["leisure", "work"],
            "ice_rink": ["leisure", "work"],
            "marina": ["leisure", "work"],
            "miniature_golf": ["leisure"],
            "nature_reserve": ["leisure"],
            "park": ["leisure"],
            "pitch": ["leisure"],
            "playground": ["leisure"],
            "sports_centre": ["leisure", "work"],
            "stadium": ["leisure", "work"],
            "swimming_pool": ["leisure", "work"],
            "track": ["leisure"],
            "water_park": ["leisure", "work"]
        },
        "office": {
            "*": ["work"]
        },
		"public_transport": {
			"*": ["transit"]
		},
		"highway": {
			"bus_stop": ["transit"]
		}
    },

	"fill_missing_activities":
    [
        {
            "area_tags": [["landuse", "residential"]],
            "required_acts": ["home"],
            "new_tags": [["building", "house"]],
            "fill_method": "spacing",
            "size": [10, 10],
            "spacing": [50, 50]
        }

    ]
}

=== arup-group/osmox/tests/fixtures/test_config_leisure.json
{
    "filter": {
        "leisure": ["pitch", "park", "playground"]
    },

    "object_features": ["units", "levels", "area", "floor_area"],

    "default_tags": [["building", "residential"]],

    "activity_mapping": {
        "leisure": {
            "park": ["leisure"],
            "playground": ["leisure"],
            "pitch": ["leisure"]
        }
    }
}

=== arup-group/osmox/configs/config_UKfill.json
{
	"filter": {
		"building": [
			"apartments",
			"bungalow",
			"detached",
			"dormitory",
			"hotel",
			"house",
			"residential",
			"semidetached_house",
			"terrace",
			"commercial",
			"retail",
			"supermarket",
			"industrial",
			"office",
			"warehouse",
			"bakehouse",
			"firestation",
			"government",
			"cathedral",
			"chapel",
			"church",
			"mosque",
			"other",
			"shrine",
			"synagogue",
			"temple",
			"hospital",
			"kindergarden",
			"school",
			"university",
			"college",
			"sports_hall",
			"stadium",
			"yes"
		],
		"public_transport": ["*"],
		"highway": ["bus_stop"]
	},

	"object_features": ["units", "levels", "area", "floor_area"],

	"distance_to_nearest": ["transit"],

	"fill_missing_activities":
		[
			{
				"area_tags": [["landuse", "residential"]],
				"required_acts": ["home"],
				"new_tags": [["building", "house"]],
				"size": [10, 10],
				"spacing": [25, 50]
			}

		],

	"default_tags": [["building", "residential"]],

	"activity_mapping": {
		"public_transport": {
			"*": ["transit"]
		},
		"highway": {
			"bus_stop": ["transit"]
		},
		"building": {
			"apartments": ["home"],
			"bungalow": ["home"],
			"detached": ["home"],
			"dormitory": ["home"],
			"hotel": ["home"],
			"house": ["home"],
			"residential": ["home"],
			"semidetached_house": ["home"],
			"terrace": ["home"],
			"commercial": ["shop", "work"],
			"retail": ["shop", "work"],
			"supermarket": ["shop", "work"],
			"industrial": ["work"],
			"office": ["work"],
			"warehouse": ["work"],
			"bakehouse": ["work"],
			"firestation": ["work"],
			"government": ["work"],
			"cathedral": ["other"],
			"chapel": ["other"],
			"church": ["other"],
			"mosque": ["other"],
			"other": ["other"],
			"shrine": ["other"],
			"synagogue": ["other"],
			"temple": ["other"],
			"hospital": ["medical", "work"],
			"kindergarden": ["education", "work"],
			"school": ["education", "work"],
			"university": ["education", "work"],
			"college": ["education", "work"],
			"sports_hall": ["other", "work"],
			"stadium": ["other", "work"]
		},
		"amenity": {
			"bar": ["visit", "work"],
			"pub": ["visit", "work"],
			"cafe": ["visit", "work", "shop"],
			"fast_food": ["work", "shop"],
			"food_court": ["work", "shop"],
			"ice_cream": ["work", "shop"],
			"restaurant": ["work", "shop"],
			"college": ["education", "work"],
			"kindergarten": ["education", "work"],
			"language_school": ["education", "work"],
			"library": ["other", "work"],
			"music_school": ["education", "work"],
			"school": ["education", "work"],
			"university": ["education", "work"],
			"bank": ["other", "work"],
			"clinic": ["medical", "work"],
			"dentist": ["medical", "work"],
			"doctors": ["medical", "work"],
			"hospital": ["medical", "work"],
			"pharmacy": ["shop", "work"],
			"visit_facility": ["medical", "work"],
			"vetinary": ["other", "work"],
			"arts_centre": ["other", "work"],
			"casino": ["other", "work"],
			"cinema": ["other", "work"],
			"community_centre": ["other"],
			"gambling": ["other", "work"],
			"studio": ["other", "work"],
			"theatre": ["other", "work"],
			"courthouse": ["other", "work"],
			"crematorium": ["other", "work"],
			"embassy": ["other", "work"],
			"fire_station": ["work"],
			"funeral_hall": ["other", "work"],
			"internet_cafe": ["other", "work"],
			"marketplace": ["shop", "work"],
			"place_of_worship": ["other"],
			"police": ["other", "work"],
			"post_box": ["other", "work"],
			"post_work": ["other", "work"],
			"post_office": ["other", "work"],
			"prison": ["other", "work"],
			"townhall": ["other", "work"]
		},
		"healthcare": {
			"*": ["medical", "work"]
		},
		"landuse": {
			"commercial": ["shop", "work"],
			"industrial": ["work"],
			"residential": ["home"],
			"retail": ["shop", "work"],
			"work": ["work"],
			"port": ["work"],
			"quary": ["work"],
			"other": ["other"]
		},
		"other": {
			"adult_gaming_centre": ["other", "work"],
			"amusement_arcade": ["other", "work"],
			"beach_resort": ["other"],
			"dance": ["other", "work"],
			"escape_game": ["other", "work"],
			"fishing": ["other"],
			"fitness_centre": ["other", "work"],
			"fitness_station": ["other"],
			"garden": ["other"],
			"horse_riding": ["other", "work"],
			"ice_rink": ["other", "work"],
			"marina": ["other", "work"],
			"miniature_golf": ["other"],
			"nature_reserve": ["other"],
			"park": ["other"],
			"pitch": ["other"],
			"playground": ["other"],
			"sports_centre": ["other", "work"],
			"stadium": ["other", "work"],
			"swimming_pool": ["other", "work"],
			"track": ["other"],
			"water_park": ["other", "work"]
		},
	"office": {
			"*": ["work"]
	},
	"shop": {
			"*": ["shop", "work"]
		}
	}
}
